esphome:
  name: eink 

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
captive_portal:

mqtt:
  broker: !secret mqtt_broker

web_server:
  port: 80
  version: 3

# Example configuration entry
font:
  - file: 'gfonts://Roboto'
    id: font1
    size: 8

spi:
  clk_pin: 13
  mosi_pin: 14

display:
  - platform: waveshare_epaper
    cs_pin: 15
    dc_pin: 27
    busy_pin: 25
    reset_pin: 26
    model: 7.50in-bV3
    update_interval: 30sec
    reset_duration: 2ms
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");