esphome:
  name: ikeamaster 

esp8266:
  board: esp12e

# Enable logging
logger:
  level: DEBUG

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


captive_portal:
    

mqtt:
  broker: !secret mqtt_broker

web_server:
  version: 3

text_sensor:
  - platform: version
    name: "Firmware Version"

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter 2.5µm Concentration"
    update_interval: 60s

uart:
  rx_pin: GPIO14
  tx_pin: GPIO13
  baud_rate: 9600