esphome:
  name: rain2

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

api:

ota:
  - platform: esphome

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker

web_server:
  port: 80
  version: 3


uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600

sensor:
  - platform: hydreon_rgxx
    model: "RG_15"
    update_interval: 60s
    acc:
      name: "rain"
    event_acc:
      name: "rain event"
    total_acc:
      name: "rain total"
    r_int:
      name: "rain intensity"

  - platform: uptime
    name: Uptime Sensor