esphome:
  name: rain

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
    

mqtt:
  broker: !secret mqtt_broker

web_server:
  version: 3

uart:
  rx_pin: GPIO12
  tx_pin: GPIO14
  baud_rate: 9600

sensor:
  - platform: hydreon_rgxx
    model: "RG_15"
    update_interval: 60s
    acc:
      name: "rain"
    event_acc:
      name: "rain event"
    total_acc:
      name: "rain total"
    r_int:
      name: "rain intensity"

  - platform: pulse_meter
    pin: 
      number: GPIO5
      mode: INPUT_PULLUP
    name: 'Windspeed Meter'
    icon: 'mdi:weather-windy'
    id: wind_meter
    unit_of_measurement: 'mph'
    accuracy_decimals: 1
    timeout: 5s
    filters:
      - multiply: 0.0124285 #1.492mph per rotation so 1 / 60 / 2 * 1.491424
      - sliding_window_moving_average: # Helps prevent too many datapoints
          window_size: 15
          send_every: 15

#
# Wind Direction
#
  - platform: adc
    id: adc_sensor
    pin: A0
    name: ADC
    internal: true
    update_interval: 5s
    filters:
      - multiply: 3.3
    accuracy_decimals: 3 ##IMPORTANT to get resolution for resistance sensor
    
### ADD WIND CARIDNAL DIRECTION
### Your values may differ!
# Direction -- Resistance -- ADC Voltage
# TODO:
# N -- 33KΩ -- 2.56v
# NE -- 8.2KΩ -- 1.5v
# E -- 1KΩ -- 0.30v
# SE -- 2.2KΩ -- 0.6v
# S -- 3.9KΩ -- 0.93v
# SW -- 16KΩ -- 2.05v
# W -- 120KΩ -- 3.07v
# NW -- 64.9KΩ -- 2.89v
  - platform: resistance
    sensor: adc_sensor
    id: resistance_sensor
    configuration: DOWNSTREAM
    resistor: 10kOhm
    internal: true
    name: Resistance Sensor
    accuracy_decimals: 1
    #filters:
      #- heartbeat: 90s
    on_value:
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 30000
              below: 50000
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "N"
            - sensor.template.publish:
                id: wind_heading
                state: 0.0
                
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 5000
              below: 10000
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "NE"         
            - sensor.template.publish:
                id: wind_heading
                state: 45.0            
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 500
              below: 1500
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "E"                
            - sensor.template.publish:
                id: wind_heading
                state: 90.0          
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 1500
              below: 3000
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "SE"    
            - sensor.template.publish:
                id: wind_heading
                state: 135.0             
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 3000
              below: 5000
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "S"    
            - sensor.template.publish:
                id: wind_heading
                state: 180.0            
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 10000
              below: 30000
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "SW"    
            - sensor.template.publish:
                id: wind_heading
                state: 225.0              
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 110000
              below: 140000
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "W"    
            - sensor.template.publish:
                id: wind_heading
                state: 270.0          
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 50000
              below: 80000
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "NW"    
            - sensor.template.publish:
                id: wind_heading
                state: 315.0

  - platform: template
    name: "Wind Heading"
    icon: 'mdi:compass-rose'
    id: wind_heading
    unit_of_measurement: "°"
    accuracy_decimals: 0
    update_interval: never
  - platform: wifi_signal
    name: Wifi Signal
    update_interval: 60s
    


  - platform: uptime
    name: Uptime Sensor

text_sensor:
  - platform: template
    name: "Wind Cardinal Direction"
    icon: "mdi:windsock"
    id: wind_dir_card
    update_interval: never